spring:
  application:
    name: userservice
  datasource:
    #    url: jdbc:mysql://localhost:3306/airlinereservation
    #    username: root
    #    password: Anju@1234
    url: jdbc:mysql://sql10.freemysqlhosting.net:3306/sql10455677
    username: sql10455677
    password: 6QJD187URY
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
